name: Docker Build & Push

on:
  push:
    branches: [ "main" ]  # Déclenche le workflow sur un push vers "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Machine virtuelle Ubuntu

    steps:
      # Étape 1 : Récupère le code
      - name: Checkout
        uses: actions/checkout@v4

      # Étape 2 : Login sur Docker Hub (si tu veux pousser l'image)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Étape 3 : Build l'image Docker
      - name: Build Docker Image
        run: docker build -t mon-site-nginx .

      # Étape 4 : Push l'image sur Docker Hub (optionnel)
      - name: Push to Docker Hub
        run: |
          docker tag mon-site-nginx ${{ secrets.DOCKER_HUB_USERNAME }}/mon-site-nginx:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mon-site-nginx:latest